### ISSUE TITLE
Multiple windows and concurrency

### ISSUE THREAD

**Issue by penciltester** [lxn/walk#297]
What is the proper way of creating multiple windows (mainWindow + dialogs) and changing their content concurrently?

I found, that every window creates new goroutine to get messages:
`switch win.GetMessage(&msg, 0, 0, 0) {`

Also, dialog.Synchronize(...) does not do the job, because runSynchronized() is a global function invoked from multiple goroutines.

Now, when there are 2 windows sometimes the dialog one gets stuck when changing content (setting value of a ProgressBar). Program panicking on concurrent map access is another thing, which can be fixed with mutexes.

Why the dialog freezes? What is the best method for creating multiple windows, or is it an API bug?

After the window gets stuck, both window goroutines are in GetMessage state, but the dialog does not respond (stacktrace debugged from another TCP goroutine).

**Comment by kjk** [comment]
Small clarification: internally, walk doesn't run message loop in a goroutine. 

You can launch it in a goroutine but you probably shouldn't. For one, `runSynchronized` is run in that goroutine and its purpose is to be run on main thread.

You only need one message pump in Windows. It's arguably unfortunate API design that `Run()` is on `FormBase` and not on some global object, like Application.

As to the problems you're describing, you probably should post a small repro program because the description is inevitably missing the details.

Not knowing the exact details of your program, I would suggest to start by only doing `Run()` on one window and only do it on the main thread. You can create more windows but only call Run() on one of them.

For good measure, call`runtime.LockOSThread` on main thread to make sure Go runtime won't reuse main thread for other goroutines.

**Comment by penciltester** [comment]
After updating Windows 8 (KB3172729) in VirtualBox I can't reproduce this error (freezing).
Also, the issue happened when the CPU was very busy.
Here's the example program, that would be stuck:
https://gist.github.com/penciltester/276ea66ae4524b13ea710c7b4ee6dd5d
Now I can't reproduce it even in the original app.

**Comment by penciltester** [comment]
Finally, I made it freeze with net/http. After several tries it is finally not responding.
In windows 8 it somehow fixed itself, but in host OS, windows 10, the bug exists.

https://gist.github.com/penciltester/0b12cf75e145bf5aaf5308c22a6b81a3

**Comment by penciltester** [comment]
When running windows with .Show() widgets are not showing.

https://gist.github.com/penciltester/bbee0e2c7d0ea7233e1068c441fb2f81

**Comment by penciltester** [comment]
Screenshot of https://gist.github.com/penciltester/0b12cf75e145bf5aaf5308c22a6b81a3
![2017-07-18_02-59-41](https://user-images.githubusercontent.com/30245551/28298371-35d2fdc8-6b73-11e7-9b3e-434a8fe6238b.png)

But adding `runtime.LockOSThread()` seems to fix the problem.

**Comment by kjk** [comment]
I've been playing with https://gist.github.com/penciltester/0b12cf75e145bf5aaf5308c22a6b81a3

The line `go askDialog()` is almost certainly wrong. askDialog creates new windows/dialogs, which involves calling functions that assume being called on main thread.

Also, call `runtime.LockOSThread()` from `main()`. God only knows when/on which thread `init` is called.

**Comment by kjk** [comment]
After making the change `go askDialog()` => `askDialog()`, I couldn't get a crash or reproduce the hang on win 10 64, using 64bit build using go 1.8.3.

If you can get `-race` to work on WIndows, it'll help you catch thread issues earlier.

Hanging in progress indicates a deadlock, most likely trying to take the same mutex twice. Like I said I couldn't reproduce the problem myself, but here the only mutex I can think of is the one use by Synchronize().

Try running under the debugger (I had luck using built-in debugging from Go extension in Visual Studio Code). When the program hangs, break and see what the goroutines are doing.

**Comment by penciltester** [comment]
Thank you for help. Everything works when form.Run() methods are nested on main thread. Nothing hangs up and walk works perfectly. Thanks!

**Comment by penciltester** [comment]
Small note: after the fix `mainWindow.ProgressIndicator()` shows progress in the taskbar only after the dialog closes.
