### ISSUE TITLE
Accessibility API is bizarre

### ISSUE THREAD

**Issue by zx2c4** [lxn/walk#623]
@rozmansi made this commit -- https://github.com/lxn/walk/commit/0bdcba701d40ae92ef8e1e65ccd14c125f28e9c3 -- which appears to break from the general style of walk, returning HRESULT, taking strange `win.` values, and generally cluttering up the WindowBase interface in weird ways.

- Does this need to be in the interface? Remember that interface methods aren't eliminated by deadcode detection in the linker.
- Can it return a usual go error type?
- Can these take a more reasonable set of input values or expose an API that's a bit more refined than the raw win32 stuff?
- Can these go into a totally distinct file?
- Based on [this commit in WireGuard](https://git.zx2c4.com/wireguard-windows/commit/?id=259821281ccba027d96137c6f10d0c6516a30156), you appear to require CoInitializeEx to be called for this to work? Really that should be called during walk initialization or on first use. But other walk components also use COM, like the taskbar interface. How do these places do it? Copy that.
- CoCreateInstance is called for each WindowBase. Shouldn't this instead live in the WindowGroup? Another misdesign.

I should have protested on the original PR, but I do not think that this accessibility commit passes muster.

**Comment by rozmansi** [comment]
Unfortunately, Dynamic Accessibility is implemented using COM objects. That's why it looks a lot different from standard Win32 API.

> which appears to break from the general style of walk, returning HRESULT, taking strange win. values, and generally cluttering up the WindowBase interface in weird ways.
> Can it return a usual go error type?

My first step was to make E_FAIL and other HRESULT constants typed as HRESULT. But this got rejected by @lxn. Presumably, because it threw compilation errors with his client dealing with HRESULT-based constants. In the next step, the HRESULT would have become an error type. This way all the methods could return simply an `error`. But, not all HRESULT values are errors. S_FALSE is not. Bit 31 is set for errors and clear for success or warning conditions.

Maybe all HRESULTs could be internally dealt within lxn/walk: in case of failure only return newError("something is wrong").

Other constants for Dynamic Accessibility would need to be redeclared in lxn/walk again. Maintaining two identical sets of constants just to keep lxn/win hidden from client is that what you propose?

> Can these take a more reasonable set of input values or expose an API that's a bit more refined than the raw win32 stuff?
> Can these go into a totally distinct file?

There was no direct need to push it to the lxn/walk - I had WireGuard use Dynamic Annotation directly from lxn/win, but you personally suggested to make it reusable. Therefore, I moved it to lxn/walk. 

> Based on this commit in WireGuard, you appear to require CoInitializeEx to be called for this to work? Really that should be called during walk initialization or on first use. But other walk components also use COM, like the taskbar interface. How do these places do it? Copy that.

lxn/walk uses legacy OleInitialize couple of times: ShowBrowseFolder initializes (or fails if different threading model already initialized) and defers uninitialization; NewWebView initializes it and uninitializes it on Dispose. Taskbar doesn't do initialization/uninitialization like my Dynamic Annotation doesn't. It just assums it is initialized by client. I followed this approach as I believe it is more correct.

MSDN says:

> OleInitialize calls CoInitializeEx internally to initialize the COM library on the current apartment. Because OLE operations are not thread-safe, OleInitialize specifies the concurrency model as single-thread apartment.
> Once the concurrency model for an apartment is set, it cannot be changed. A call to OleInitialize on an apartment that was previously initialized as multithreaded will fail and return RPC_E_CHANGED_MODE.

This means that clients using lxn/walk are forced to use single-threaded apartment if they want to use browse folder dialog or web view.

I believe better approach would be to restrain from initializing/uninitializing COM in lxn/walk completely. Clients that would require the parts of the lxn/walk library that needs COM would see it fail and be advised to initialize COM themselves using the thread model they desire. Maybe they use COM for other things too and would prefer a different thread model?

> CoCreateInstance is called for each WindowBase. Shouldn't this instead live in the WindowGroup? Another misdesign.

It is not called for each WindowBase. It is called on demand. The `accPropServices` stays nil if nobody uses Dynamic Annotation. WindowGroup would be a possible place, but we need to decide if lxn/walk really starts initializing COM by itself and which COM thread model will it force clients to: apartment threaded or free threaded. If later is picked, we'd need to add mutex to sync accPropServices member calls.

But you are right: in general one IAccPropServices object would do for entire application.
